apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-0qyb
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0044-tenant/tkrw-pr712-0075-0044-app/devfile-sample-0qyb@sha256:8a6fbcf9c34975c41343e8c82b7daa5670335793823f195e74d07839483f9672
        name: my-nodejs
        resources: {}
status: {}
